name:  Create Production Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Source release candidate (Ex.: v1.0.1-rc1)'
        required: true

jobs:
  production-promotion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: release-gate-prod
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }

      - name: Finalize Release
        run: |
          
          #git config --global user.email "automation@example.com"
          #git config --global user.name "Githubaction automation"
          
          RCVERSION=${{ github.event.inputs.version }}
          STABLE_VERSION=${RCVERSION%-*}
          git checkout main
          git merge ${{ github.event.inputs.version }}
          git tag ${STABLE_VERSION}
          git push origin main ${STABLE_VERSION}
